from pypacks.resources.custom_item import CustomItem
from pypacks.additions.item_components import AttributeModifier, Components, Equippable, Tool, ToolRule

ANCIENT_DEBRIS = CustomItem(internal_name="minecraft:ancient_debris", base_item="ancient_debris", components=Components(damage_resistant_to='#minecraft:is_fire'))
CHAINMAIL_BOOTS = CustomItem(internal_name="minecraft:chainmail_boots", base_item="chainmail_boots", components=Components(enchantable_at_level=12, repaired_by=['#minecraft:repairs_chain_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='feet', amount=1.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='feet', amount=0.0, operation='add_value')], equippable=Equippable(slot='feet', equip_sound='minecraft:item.armor.equip_chain', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1, rarity="uncommon")
CHAINMAIL_CHESTPLATE = CustomItem(internal_name="minecraft:chainmail_chestplate", base_item="chainmail_chestplate", components=Components(enchantable_at_level=12, repaired_by=['#minecraft:repairs_chain_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='chest', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='chest', amount=0.0, operation='add_value')], equippable=Equippable(slot='chest', equip_sound='minecraft:item.armor.equip_chain', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1, rarity="uncommon")
CHAINMAIL_HELMET = CustomItem(internal_name="minecraft:chainmail_helmet", base_item="chainmail_helmet", components=Components(enchantable_at_level=12, repaired_by=['#minecraft:repairs_chain_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=0.0, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_chain', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1, rarity="uncommon")
CHAINMAIL_LEGGINGS = CustomItem(internal_name="minecraft:chainmail_leggings", base_item="chainmail_leggings", components=Components(enchantable_at_level=12, repaired_by=['#minecraft:repairs_chain_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='legs', amount=4.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='legs', amount=0.0, operation='add_value')], equippable=Equippable(slot='legs', equip_sound='minecraft:item.armor.equip_chain', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1, rarity="uncommon")
DIAMOND_AXE = CustomItem(internal_name="minecraft:diamond_axe", base_item="diamond_axe", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:diamond_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=8.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_diamond_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/axe', speed=8.0, correct_for_drops=True)])), max_stack_size=1)
DIAMOND_BOOTS = CustomItem(internal_name="minecraft:diamond_boots", base_item="diamond_boots", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:repairs_diamond_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='feet', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='feet', amount=2.0, operation='add_value')], equippable=Equippable(slot='feet', equip_sound='minecraft:item.armor.equip_diamond', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
DIAMOND_CHESTPLATE = CustomItem(internal_name="minecraft:diamond_chestplate", base_item="diamond_chestplate", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:repairs_diamond_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='chest', amount=8.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='chest', amount=2.0, operation='add_value')], equippable=Equippable(slot='chest', equip_sound='minecraft:item.armor.equip_diamond', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
DIAMOND_HELMET = CustomItem(internal_name="minecraft:diamond_helmet", base_item="diamond_helmet", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:repairs_diamond_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=2.0, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_diamond', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
DIAMOND_HOE = CustomItem(internal_name="minecraft:diamond_hoe", base_item="diamond_hoe", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:diamond_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=0.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=0.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_diamond_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/hoe', speed=8.0, correct_for_drops=True)])), max_stack_size=1)
DIAMOND_HORSE_ARMOR = CustomItem(internal_name="minecraft:diamond_horse_armor", base_item="diamond_horse_armor", components=Components(attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='body', amount=11.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='body', amount=2.0, operation='add_value')], equippable=Equippable(slot='body', equip_sound='minecraft:entity.horse.armor', dispensable=True, swappable=True, entities_which_can_wear=[])), max_stack_size=1)
DIAMOND_LEGGINGS = CustomItem(internal_name="minecraft:diamond_leggings", base_item="diamond_leggings", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:repairs_diamond_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='legs', amount=6.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='legs', amount=2.0, operation='add_value')], equippable=Equippable(slot='legs', equip_sound='minecraft:item.armor.equip_diamond', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
DIAMOND_PICKAXE = CustomItem(internal_name="minecraft:diamond_pickaxe", base_item="diamond_pickaxe", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:diamond_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=4.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.8, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_diamond_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/pickaxe', speed=8.0, correct_for_drops=True)])), max_stack_size=1)
DIAMOND_SHOVEL = CustomItem(internal_name="minecraft:diamond_shovel", base_item="diamond_shovel", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:diamond_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=4.5, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_diamond_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/shovel', speed=8.0, correct_for_drops=True)])), max_stack_size=1)
DIAMOND_SWORD = CustomItem(internal_name="minecraft:diamond_sword", base_item="diamond_sword", components=Components(enchantable_at_level=10, repaired_by=['#minecraft:diamond_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=6.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[ToolRule(blocks='minecraft:cobweb', speed=15.0, correct_for_drops=True), ToolRule(blocks='#minecraft:sword_efficient', speed=1.5, correct_for_drops=True)])), max_stack_size=1)
GOLDEN_AXE = CustomItem(internal_name="minecraft:golden_axe", base_item="golden_axe", components=Components(enchantable_at_level=22, repaired_by=['#minecraft:gold_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=6.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_gold_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/axe', speed=12.0, correct_for_drops=True)])), max_stack_size=1)
GOLDEN_BOOTS = CustomItem(internal_name="minecraft:golden_boots", base_item="golden_boots", components=Components(enchantable_at_level=25, repaired_by=['#minecraft:repairs_gold_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='feet', amount=1.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='feet', amount=0.0, operation='add_value')], equippable=Equippable(slot='feet', equip_sound='minecraft:item.armor.equip_gold', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
GOLDEN_CHESTPLATE = CustomItem(internal_name="minecraft:golden_chestplate", base_item="golden_chestplate", components=Components(enchantable_at_level=25, repaired_by=['#minecraft:repairs_gold_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='chest', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='chest', amount=0.0, operation='add_value')], equippable=Equippable(slot='chest', equip_sound='minecraft:item.armor.equip_gold', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
GOLDEN_HELMET = CustomItem(internal_name="minecraft:golden_helmet", base_item="golden_helmet", components=Components(enchantable_at_level=25, repaired_by=['#minecraft:repairs_gold_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=0.0, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_gold', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
GOLDEN_HOE = CustomItem(internal_name="minecraft:golden_hoe", base_item="golden_hoe", components=Components(enchantable_at_level=22, repaired_by=['#minecraft:gold_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=0.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_gold_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/hoe', speed=12.0, correct_for_drops=True)])), max_stack_size=1)
GOLDEN_HORSE_ARMOR = CustomItem(internal_name="minecraft:golden_horse_armor", base_item="golden_horse_armor", components=Components(attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='body', amount=7.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='body', amount=0.0, operation='add_value')], equippable=Equippable(slot='body', equip_sound='minecraft:entity.horse.armor', dispensable=True, swappable=True, entities_which_can_wear=[])), max_stack_size=1)
GOLDEN_LEGGINGS = CustomItem(internal_name="minecraft:golden_leggings", base_item="golden_leggings", components=Components(enchantable_at_level=25, repaired_by=['#minecraft:repairs_gold_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='legs', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='legs', amount=0.0, operation='add_value')], equippable=Equippable(slot='legs', equip_sound='minecraft:item.armor.equip_gold', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
GOLDEN_PICKAXE = CustomItem(internal_name="minecraft:golden_pickaxe", base_item="golden_pickaxe", components=Components(enchantable_at_level=22, repaired_by=['#minecraft:gold_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=1.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.8, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_gold_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/pickaxe', speed=12.0, correct_for_drops=True)])), max_stack_size=1)
GOLDEN_SHOVEL = CustomItem(internal_name="minecraft:golden_shovel", base_item="golden_shovel", components=Components(enchantable_at_level=22, repaired_by=['#minecraft:gold_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=1.5, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_gold_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/shovel', speed=12.0, correct_for_drops=True)])), max_stack_size=1)
GOLDEN_SWORD = CustomItem(internal_name="minecraft:golden_sword", base_item="golden_sword", components=Components(enchantable_at_level=22, repaired_by=['#minecraft:gold_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[ToolRule(blocks='minecraft:cobweb', speed=15.0, correct_for_drops=True), ToolRule(blocks='#minecraft:sword_efficient', speed=1.5, correct_for_drops=True)])), max_stack_size=1)
IRON_AXE = CustomItem(internal_name="minecraft:iron_axe", base_item="iron_axe", components=Components(enchantable_at_level=14, repaired_by=['#minecraft:iron_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=8.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.1, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_iron_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/axe', speed=6.0, correct_for_drops=True)])), max_stack_size=1)
IRON_BOOTS = CustomItem(internal_name="minecraft:iron_boots", base_item="iron_boots", components=Components(enchantable_at_level=9, repaired_by=['#minecraft:repairs_iron_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='feet', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='feet', amount=0.0, operation='add_value')], equippable=Equippable(slot='feet', equip_sound='minecraft:item.armor.equip_iron', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
IRON_CHESTPLATE = CustomItem(internal_name="minecraft:iron_chestplate", base_item="iron_chestplate", components=Components(enchantable_at_level=9, repaired_by=['#minecraft:repairs_iron_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='chest', amount=6.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='chest', amount=0.0, operation='add_value')], equippable=Equippable(slot='chest', equip_sound='minecraft:item.armor.equip_iron', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
IRON_HELMET = CustomItem(internal_name="minecraft:iron_helmet", base_item="iron_helmet", components=Components(enchantable_at_level=9, repaired_by=['#minecraft:repairs_iron_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=0.0, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_iron', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
IRON_HOE = CustomItem(internal_name="minecraft:iron_hoe", base_item="iron_hoe", components=Components(enchantable_at_level=14, repaired_by=['#minecraft:iron_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=0.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-1.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_iron_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/hoe', speed=6.0, correct_for_drops=True)])), max_stack_size=1)
IRON_HORSE_ARMOR = CustomItem(internal_name="minecraft:iron_horse_armor", base_item="iron_horse_armor", components=Components(attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='body', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='body', amount=0.0, operation='add_value')], equippable=Equippable(slot='body', equip_sound='minecraft:entity.horse.armor', dispensable=True, swappable=True, entities_which_can_wear=[])), max_stack_size=1)
IRON_LEGGINGS = CustomItem(internal_name="minecraft:iron_leggings", base_item="iron_leggings", components=Components(enchantable_at_level=9, repaired_by=['#minecraft:repairs_iron_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='legs', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='legs', amount=0.0, operation='add_value')], equippable=Equippable(slot='legs', equip_sound='minecraft:item.armor.equip_iron', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
IRON_PICKAXE = CustomItem(internal_name="minecraft:iron_pickaxe", base_item="iron_pickaxe", components=Components(enchantable_at_level=14, repaired_by=['#minecraft:iron_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.8, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_iron_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/pickaxe', speed=6.0, correct_for_drops=True)])), max_stack_size=1)
IRON_SHOVEL = CustomItem(internal_name="minecraft:iron_shovel", base_item="iron_shovel", components=Components(enchantable_at_level=14, repaired_by=['#minecraft:iron_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=3.5, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_iron_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/shovel', speed=6.0, correct_for_drops=True)])), max_stack_size=1)
IRON_SWORD = CustomItem(internal_name="minecraft:iron_sword", base_item="iron_sword", components=Components(enchantable_at_level=14, repaired_by=['#minecraft:iron_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[ToolRule(blocks='minecraft:cobweb', speed=15.0, correct_for_drops=True), ToolRule(blocks='#minecraft:sword_efficient', speed=1.5, correct_for_drops=True)])), max_stack_size=1)
LEATHER_BOOTS = CustomItem(internal_name="minecraft:leather_boots", base_item="leather_boots", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_leather_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='feet', amount=1.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='feet', amount=0.0, operation='add_value')], equippable=Equippable(slot='feet', equip_sound='minecraft:item.armor.equip_leather', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
LEATHER_CHESTPLATE = CustomItem(internal_name="minecraft:leather_chestplate", base_item="leather_chestplate", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_leather_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='chest', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='chest', amount=0.0, operation='add_value')], equippable=Equippable(slot='chest', equip_sound='minecraft:item.armor.equip_leather', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
LEATHER_HELMET = CustomItem(internal_name="minecraft:leather_helmet", base_item="leather_helmet", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_leather_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=1.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=0.0, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_leather', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
LEATHER_HORSE_ARMOR = CustomItem(internal_name="minecraft:leather_horse_armor", base_item="leather_horse_armor", components=Components(attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='body', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='body', amount=0.0, operation='add_value')], equippable=Equippable(slot='body', equip_sound='minecraft:entity.horse.armor', dispensable=True, swappable=True, entities_which_can_wear=[])), max_stack_size=1)
LEATHER_LEGGINGS = CustomItem(internal_name="minecraft:leather_leggings", base_item="leather_leggings", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_leather_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='legs', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='legs', amount=0.0, operation='add_value')], equippable=Equippable(slot='legs', equip_sound='minecraft:item.armor.equip_leather', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
MACE = CustomItem(internal_name="minecraft:mace", base_item="mace", components=Components(enchantable_at_level=15, repaired_by=['minecraft:breeze_rod'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[])), max_stack_size=1, rarity="epic")
NETHER_STAR = CustomItem(internal_name="minecraft:nether_star", base_item="nether_star", components=Components(damage_resistant_to='#minecraft:is_explosion'), rarity="rare")
NETHERITE_AXE = CustomItem(internal_name="minecraft:netherite_axe", base_item="netherite_axe", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:netherite_tool_materials'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=9.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_netherite_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/axe', speed=9.0, correct_for_drops=True)])), max_stack_size=1)
NETHERITE_BLOCK = CustomItem(internal_name="minecraft:netherite_block", base_item="netherite_block", components=Components(damage_resistant_to='#minecraft:is_fire'))
NETHERITE_BOOTS = CustomItem(internal_name="minecraft:netherite_boots", base_item="netherite_boots", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_netherite_armor'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='feet', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='feet', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='knockback_resistance', slot='feet', amount=0.1, operation='add_value')], equippable=Equippable(slot='feet', equip_sound='minecraft:item.armor.equip_netherite', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
NETHERITE_CHESTPLATE = CustomItem(internal_name="minecraft:netherite_chestplate", base_item="netherite_chestplate", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_netherite_armor'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='chest', amount=8.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='chest', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='knockback_resistance', slot='chest', amount=0.1, operation='add_value')], equippable=Equippable(slot='chest', equip_sound='minecraft:item.armor.equip_netherite', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
NETHERITE_HELMET = CustomItem(internal_name="minecraft:netherite_helmet", base_item="netherite_helmet", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_netherite_armor'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='knockback_resistance', slot='head', amount=0.1, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_netherite', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
NETHERITE_HOE = CustomItem(internal_name="minecraft:netherite_hoe", base_item="netherite_hoe", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:netherite_tool_materials'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=0.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=0.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_netherite_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/hoe', speed=9.0, correct_for_drops=True)])), max_stack_size=1)
NETHERITE_INGOT = CustomItem(internal_name="minecraft:netherite_ingot", base_item="netherite_ingot", components=Components(damage_resistant_to='#minecraft:is_fire'))
NETHERITE_LEGGINGS = CustomItem(internal_name="minecraft:netherite_leggings", base_item="netherite_leggings", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:repairs_netherite_armor'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='legs', amount=6.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='legs', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='knockback_resistance', slot='legs', amount=0.1, operation='add_value')], equippable=Equippable(slot='legs', equip_sound='minecraft:item.armor.equip_netherite', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
NETHERITE_PICKAXE = CustomItem(internal_name="minecraft:netherite_pickaxe", base_item="netherite_pickaxe", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:netherite_tool_materials'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=5.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.8, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_netherite_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/pickaxe', speed=9.0, correct_for_drops=True)])), max_stack_size=1)
NETHERITE_SCRAP = CustomItem(internal_name="minecraft:netherite_scrap", base_item="netherite_scrap", components=Components(damage_resistant_to='#minecraft:is_fire'))
NETHERITE_SHOVEL = CustomItem(internal_name="minecraft:netherite_shovel", base_item="netherite_shovel", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:netherite_tool_materials'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=5.5, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_netherite_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/shovel', speed=9.0, correct_for_drops=True)])), max_stack_size=1)
NETHERITE_SWORD = CustomItem(internal_name="minecraft:netherite_sword", base_item="netherite_sword", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:netherite_tool_materials'], damage_resistant_to='#minecraft:is_fire', attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=7.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[ToolRule(blocks='minecraft:cobweb', speed=15.0, correct_for_drops=True), ToolRule(blocks='#minecraft:sword_efficient', speed=1.5, correct_for_drops=True)])), max_stack_size=1)
STONE_AXE = CustomItem(internal_name="minecraft:stone_axe", base_item="stone_axe", components=Components(enchantable_at_level=5, repaired_by=['#minecraft:stone_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=8.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.2, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_stone_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/axe', speed=4.0, correct_for_drops=True)])), max_stack_size=1)
STONE_HOE = CustomItem(internal_name="minecraft:stone_hoe", base_item="stone_hoe", components=Components(enchantable_at_level=5, repaired_by=['#minecraft:stone_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=0.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_stone_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/hoe', speed=4.0, correct_for_drops=True)])), max_stack_size=1)
STONE_PICKAXE = CustomItem(internal_name="minecraft:stone_pickaxe", base_item="stone_pickaxe", components=Components(enchantable_at_level=5, repaired_by=['#minecraft:stone_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.8, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_stone_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/pickaxe', speed=4.0, correct_for_drops=True)])), max_stack_size=1)
STONE_SHOVEL = CustomItem(internal_name="minecraft:stone_shovel", base_item="stone_shovel", components=Components(enchantable_at_level=5, repaired_by=['#minecraft:stone_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=2.5, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_stone_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/shovel', speed=4.0, correct_for_drops=True)])), max_stack_size=1)
STONE_SWORD = CustomItem(internal_name="minecraft:stone_sword", base_item="stone_sword", components=Components(enchantable_at_level=5, repaired_by=['#minecraft:stone_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=4.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[ToolRule(blocks='minecraft:cobweb', speed=15.0, correct_for_drops=True), ToolRule(blocks='#minecraft:sword_efficient', speed=1.5, correct_for_drops=True)])), max_stack_size=1)
TRIDENT = CustomItem(internal_name="minecraft:trident", base_item="trident", components=Components(enchantable_at_level=1, attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=8.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.9, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[])), max_stack_size=1, rarity="rare")
TURTLE_HELMET = CustomItem(internal_name="minecraft:turtle_helmet", base_item="turtle_helmet", components=Components(enchantable_at_level=9, repaired_by=['#minecraft:repairs_turtle_helmet'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='head', amount=2.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='head', amount=0.0, operation='add_value')], equippable=Equippable(slot='head', equip_sound='minecraft:item.armor.equip_turtle', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
WOLF_ARMOR = CustomItem(internal_name="minecraft:wolf_armor", base_item="wolf_armor", components=Components(repaired_by=['#minecraft:repairs_wolf_armor'], attribute_modifiers=[AttributeModifier(attribute_type='armor', slot='body', amount=11.0, operation='add_value'), AttributeModifier(attribute_type='armor_toughness', slot='body', amount=0.0, operation='add_value')], equippable=Equippable(slot='body', equip_sound='minecraft:item.armor.equip_wolf', dispensable=True, swappable=True, damage_on_hurt=True, entities_which_can_wear=[])), max_stack_size=1)
WOODEN_AXE = CustomItem(internal_name="minecraft:wooden_axe", base_item="wooden_axe", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:wooden_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=6.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.2, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_wooden_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/axe', speed=2.0, correct_for_drops=True)])), max_stack_size=1)
WOODEN_HOE = CustomItem(internal_name="minecraft:wooden_hoe", base_item="wooden_hoe", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:wooden_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=0.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_wooden_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/hoe', speed=2.0, correct_for_drops=True)])), max_stack_size=1)
WOODEN_PICKAXE = CustomItem(internal_name="minecraft:wooden_pickaxe", base_item="wooden_pickaxe", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:wooden_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=1.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.8, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_wooden_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/pickaxe', speed=2.0, correct_for_drops=True)])), max_stack_size=1)
WOODEN_SHOVEL = CustomItem(internal_name="minecraft:wooden_shovel", base_item="wooden_shovel", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:wooden_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=1.5, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-3.0, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=1, rules=[ToolRule(blocks='#minecraft:incorrect_for_wooden_tool', speed=1.0, correct_for_drops=False), ToolRule(blocks='#minecraft:mineable/shovel', speed=2.0, correct_for_drops=True)])), max_stack_size=1)
WOODEN_SWORD = CustomItem(internal_name="minecraft:wooden_sword", base_item="wooden_sword", components=Components(enchantable_at_level=15, repaired_by=['#minecraft:wooden_tool_materials'], attribute_modifiers=[AttributeModifier(attribute_type='attack_damage', slot='mainhand', amount=3.0, operation='add_value'), AttributeModifier(attribute_type='attack_speed', slot='mainhand', amount=-2.4, operation='add_value')], tool=Tool(default_mining_speed=1.0, damage_per_block=2, rules=[ToolRule(blocks='minecraft:cobweb', speed=15.0, correct_for_drops=True), ToolRule(blocks='#minecraft:sword_efficient', speed=1.5, correct_for_drops=True)])), max_stack_size=1)

DEFAULT_ITEMS = {
    "ANCIENT_DEBRIS": ANCIENT_DEBRIS,
    "CHAINMAIL_BOOTS": CHAINMAIL_BOOTS,
    "CHAINMAIL_CHESTPLATE": CHAINMAIL_CHESTPLATE,
    "CHAINMAIL_HELMET": CHAINMAIL_HELMET,
    "CHAINMAIL_LEGGINGS": CHAINMAIL_LEGGINGS,
    "DIAMOND_AXE": DIAMOND_AXE,
    "DIAMOND_BOOTS": DIAMOND_BOOTS,
    "DIAMOND_CHESTPLATE": DIAMOND_CHESTPLATE,
    "DIAMOND_HELMET": DIAMOND_HELMET,
    "DIAMOND_HOE": DIAMOND_HOE,
    "DIAMOND_HORSE_ARMOR": DIAMOND_HORSE_ARMOR,
    "DIAMOND_LEGGINGS": DIAMOND_LEGGINGS,
    "DIAMOND_PICKAXE": DIAMOND_PICKAXE,
    "DIAMOND_SHOVEL": DIAMOND_SHOVEL,
    "DIAMOND_SWORD": DIAMOND_SWORD,
    "GOLDEN_AXE": GOLDEN_AXE,
    "GOLDEN_BOOTS": GOLDEN_BOOTS,
    "GOLDEN_CHESTPLATE": GOLDEN_CHESTPLATE,
    "GOLDEN_HELMET": GOLDEN_HELMET,
    "GOLDEN_HOE": GOLDEN_HOE,
    "GOLDEN_HORSE_ARMOR": GOLDEN_HORSE_ARMOR,
    "GOLDEN_LEGGINGS": GOLDEN_LEGGINGS,
    "GOLDEN_PICKAXE": GOLDEN_PICKAXE,
    "GOLDEN_SHOVEL": GOLDEN_SHOVEL,
    "GOLDEN_SWORD": GOLDEN_SWORD,
    "IRON_AXE": IRON_AXE,
    "IRON_BOOTS": IRON_BOOTS,
    "IRON_CHESTPLATE": IRON_CHESTPLATE,
    "IRON_HELMET": IRON_HELMET,
    "IRON_HOE": IRON_HOE,
    "IRON_HORSE_ARMOR": IRON_HORSE_ARMOR,
    "IRON_LEGGINGS": IRON_LEGGINGS,
    "IRON_PICKAXE": IRON_PICKAXE,
    "IRON_SHOVEL": IRON_SHOVEL,
    "IRON_SWORD": IRON_SWORD,
    "LEATHER_BOOTS": LEATHER_BOOTS,
    "LEATHER_CHESTPLATE": LEATHER_CHESTPLATE,
    "LEATHER_HELMET": LEATHER_HELMET,
    "LEATHER_HORSE_ARMOR": LEATHER_HORSE_ARMOR,
    "LEATHER_LEGGINGS": LEATHER_LEGGINGS,
    "MACE": MACE,
    "NETHER_STAR": NETHER_STAR,
    "NETHERITE_AXE": NETHERITE_AXE,
    "NETHERITE_BLOCK": NETHERITE_BLOCK,
    "NETHERITE_BOOTS": NETHERITE_BOOTS,
    "NETHERITE_CHESTPLATE": NETHERITE_CHESTPLATE,
    "NETHERITE_HELMET": NETHERITE_HELMET,
    "NETHERITE_HOE": NETHERITE_HOE,
    "NETHERITE_INGOT": NETHERITE_INGOT,
    "NETHERITE_LEGGINGS": NETHERITE_LEGGINGS,
    "NETHERITE_PICKAXE": NETHERITE_PICKAXE,
    "NETHERITE_SCRAP": NETHERITE_SCRAP,
    "NETHERITE_SHOVEL": NETHERITE_SHOVEL,
    "NETHERITE_SWORD": NETHERITE_SWORD,
    "STONE_AXE": STONE_AXE,
    "STONE_HOE": STONE_HOE,
    "STONE_PICKAXE": STONE_PICKAXE,
    "STONE_SHOVEL": STONE_SHOVEL,
    "STONE_SWORD": STONE_SWORD,
    "TRIDENT": TRIDENT,
    "TURTLE_HELMET": TURTLE_HELMET,
    "WOLF_ARMOR": WOLF_ARMOR,
    "WOODEN_AXE": WOODEN_AXE,
    "WOODEN_HOE": WOODEN_HOE,
    "WOODEN_PICKAXE": WOODEN_PICKAXE,
    "WOODEN_SHOVEL": WOODEN_SHOVEL,
    "WOODEN_SWORD": WOODEN_SWORD,
}
