from pypacks.resources.custom_damage_type import CustomDamageType


ARROW = CustomDamageType(internal_name='arrow', exhaustion=0.1, scaling='when_caused_by_living_non_player')
BADRESPAWNPOINT = CustomDamageType(internal_name='badRespawnPoint', exhaustion=0.1, scaling='always', death_message_type='intentional_game_design')
CACTUS = CustomDamageType(internal_name='cactus', exhaustion=0.1, scaling='when_caused_by_living_non_player')
INFIRE = CustomDamageType(internal_name='inFire', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='burning')
CRAMMING = CustomDamageType(internal_name='cramming', scaling='when_caused_by_living_non_player')
DRAGONBREATH = CustomDamageType(internal_name='dragonBreath', scaling='when_caused_by_living_non_player')
DROWN = CustomDamageType(internal_name='drown', scaling='when_caused_by_living_non_player', effects='drowning')
DRYOUT = CustomDamageType(internal_name='dryout', exhaustion=0.1, scaling='when_caused_by_living_non_player')
FALL = CustomDamageType(internal_name='fall', scaling='when_caused_by_living_non_player', death_message_type='fall_variants')
EXPLOSION = CustomDamageType(internal_name='explosion', exhaustion=0.1, scaling='always')
FALL = CustomDamageType(internal_name='fall', scaling='when_caused_by_living_non_player', death_message_type='fall_variants')
ANVIL = CustomDamageType(internal_name='anvil', exhaustion=0.1, scaling='when_caused_by_living_non_player')
FALLINGBLOCK = CustomDamageType(internal_name='fallingBlock', exhaustion=0.1, scaling='when_caused_by_living_non_player')
FALLINGSTALACTITE = CustomDamageType(internal_name='fallingStalactite', exhaustion=0.1, scaling='when_caused_by_living_non_player')
FIREBALL = CustomDamageType(internal_name='fireball', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='burning')
FIREWORKS = CustomDamageType(internal_name='fireworks', exhaustion=0.1, scaling='when_caused_by_living_non_player')
FLYINTOWALL = CustomDamageType(internal_name='flyIntoWall', scaling='when_caused_by_living_non_player')
FREEZE = CustomDamageType(internal_name='freeze', scaling='when_caused_by_living_non_player', effects='freezing')
GENERIC = CustomDamageType(internal_name='generic', scaling='when_caused_by_living_non_player')
GENERICKILL = CustomDamageType(internal_name='genericKill', scaling='when_caused_by_living_non_player')
HOTFLOOR = CustomDamageType(internal_name='hotFloor', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='burning')
INFIRE = CustomDamageType(internal_name='inFire', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='burning')
INWALL = CustomDamageType(internal_name='inWall', scaling='when_caused_by_living_non_player')
INDIRECTMAGIC = CustomDamageType(internal_name='indirectMagic', scaling='when_caused_by_living_non_player')
LAVA = CustomDamageType(internal_name='lava', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='burning')
LIGHTNINGBOLT = CustomDamageType(internal_name='lightningBolt', exhaustion=0.1, scaling='when_caused_by_living_non_player')
MACE_SMASH = CustomDamageType(internal_name='mace_smash', exhaustion=0.1, scaling='when_caused_by_living_non_player')
MAGIC = CustomDamageType(internal_name='magic', scaling='when_caused_by_living_non_player')
MOB = CustomDamageType(internal_name='mob', exhaustion=0.1, scaling='when_caused_by_living_non_player')
MOB = CustomDamageType(internal_name='mob', exhaustion=0.1, scaling='when_caused_by_living_non_player')
MOB = CustomDamageType(internal_name='mob', exhaustion=0.1, scaling='when_caused_by_living_non_player')
ONFIRE = CustomDamageType(internal_name='onFire', scaling='when_caused_by_living_non_player', effects='burning')
OUTOFWORLD = CustomDamageType(internal_name='outOfWorld', scaling='when_caused_by_living_non_player')
OUTSIDEBORDER = CustomDamageType(internal_name='outsideBorder', scaling='when_caused_by_living_non_player')
PLAYER = CustomDamageType(internal_name='player', exhaustion=0.1, scaling='when_caused_by_living_non_player')
EXPLOSION_PLAYER = CustomDamageType(internal_name='explosion_player', exhaustion=0.1, scaling='always')
SONIC_BOOM = CustomDamageType(internal_name='sonic_boom', scaling='always')
MOB = CustomDamageType(internal_name='mob', exhaustion=0.1, scaling='when_caused_by_living_non_player')
STALAGMITE = CustomDamageType(internal_name='stalagmite', scaling='when_caused_by_living_non_player')
STARVE = CustomDamageType(internal_name='starve', scaling='when_caused_by_living_non_player')
STING = CustomDamageType(internal_name='sting', exhaustion=0.1, scaling='when_caused_by_living_non_player')
SWEETBERRYBUSH = CustomDamageType(internal_name='sweetBerryBush', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='poking')
THORNS = CustomDamageType(internal_name='thorns', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='thorns')
THROWN = CustomDamageType(internal_name='thrown', exhaustion=0.1, scaling='when_caused_by_living_non_player')
TRIDENT = CustomDamageType(internal_name='trident', exhaustion=0.1, scaling='when_caused_by_living_non_player')
ONFIRE = CustomDamageType(internal_name='onFire', exhaustion=0.1, scaling='when_caused_by_living_non_player', effects='burning')
MOB = CustomDamageType(internal_name='mob', exhaustion=0.1, scaling='when_caused_by_living_non_player')
WITHER = CustomDamageType(internal_name='wither', scaling='when_caused_by_living_non_player')
WITHERSKULL = CustomDamageType(internal_name='witherSkull', exhaustion=0.1, scaling='when_caused_by_living_non_player')
