from pypacks.resources.custom_enchantment import CustomEnchantment


AQUA_AFFINITY = CustomEnchantment(internal_name='aqua_affinity', description='enchantment.minecraft.aqua_affinity', slots=['head'])
BANE_OF_ARTHROPODS = CustomEnchantment(internal_name='bane_of_arthropods', description='enchantment.minecraft.bane_of_arthropods', slots=['mainhand'])
BINDING_CURSE = CustomEnchantment(internal_name='binding_curse', description='enchantment.minecraft.binding_curse', slots=['armor'])
BLAST_PROTECTION = CustomEnchantment(internal_name='blast_protection', description='enchantment.minecraft.blast_protection', slots=['armor'])
BREACH = CustomEnchantment(internal_name='breach', description='enchantment.minecraft.breach', slots=['mainhand'])
CHANNELING = CustomEnchantment(internal_name='channeling', description='enchantment.minecraft.channeling', slots=['mainhand'])
DENSITY = CustomEnchantment(internal_name='density', description='enchantment.minecraft.density', slots=['mainhand'])
DEPTH_STRIDER = CustomEnchantment(internal_name='depth_strider', description='enchantment.minecraft.depth_strider', slots=['feet'])
EFFICIENCY = CustomEnchantment(internal_name='efficiency', description='enchantment.minecraft.efficiency', slots=['mainhand'])
FEATHER_FALLING = CustomEnchantment(internal_name='feather_falling', description='enchantment.minecraft.feather_falling', slots=['armor'])
FIRE_ASPECT = CustomEnchantment(internal_name='fire_aspect', description='enchantment.minecraft.fire_aspect', slots=['mainhand'])
FIRE_PROTECTION = CustomEnchantment(internal_name='fire_protection', description='enchantment.minecraft.fire_protection', slots=['armor'])
FLAME = CustomEnchantment(internal_name='flame', description='enchantment.minecraft.flame', slots=['mainhand'])
FORTUNE = CustomEnchantment(internal_name='fortune', description='enchantment.minecraft.fortune', slots=['mainhand'])
FROST_WALKER = CustomEnchantment(internal_name='frost_walker', description='enchantment.minecraft.frost_walker', slots=['feet'])
IMPALING = CustomEnchantment(internal_name='impaling', description='enchantment.minecraft.impaling', slots=['mainhand'])
INFINITY = CustomEnchantment(internal_name='infinity', description='enchantment.minecraft.infinity', slots=['mainhand'])
KNOCKBACK = CustomEnchantment(internal_name='knockback', description='enchantment.minecraft.knockback', slots=['mainhand'])
LOOTING = CustomEnchantment(internal_name='looting', description='enchantment.minecraft.looting', slots=['mainhand'])
LOYALTY = CustomEnchantment(internal_name='loyalty', description='enchantment.minecraft.loyalty', slots=['mainhand'])
LUCK_OF_THE_SEA = CustomEnchantment(internal_name='luck_of_the_sea', description='enchantment.minecraft.luck_of_the_sea', slots=['mainhand'])
LURE = CustomEnchantment(internal_name='lure', description='enchantment.minecraft.lure', slots=['mainhand'])
MENDING = CustomEnchantment(internal_name='mending', description='enchantment.minecraft.mending', slots=['any'])
MULTISHOT = CustomEnchantment(internal_name='multishot', description='enchantment.minecraft.multishot', slots=['mainhand'])
PIERCING = CustomEnchantment(internal_name='piercing', description='enchantment.minecraft.piercing', slots=['mainhand'])
POWER = CustomEnchantment(internal_name='power', description='enchantment.minecraft.power', slots=['mainhand'])
PROJECTILE_PROTECTION = CustomEnchantment(internal_name='projectile_protection', description='enchantment.minecraft.projectile_protection', slots=['armor'])
PROTECTION = CustomEnchantment(internal_name='protection', description='enchantment.minecraft.protection', slots=['armor'])
PUNCH = CustomEnchantment(internal_name='punch', description='enchantment.minecraft.punch', slots=['mainhand'])
QUICK_CHARGE = CustomEnchantment(internal_name='quick_charge', description='enchantment.minecraft.quick_charge', slots=['mainhand', 'offhand'])
RESPIRATION = CustomEnchantment(internal_name='respiration', description='enchantment.minecraft.respiration', slots=['head'])
RIPTIDE = CustomEnchantment(internal_name='riptide', description='enchantment.minecraft.riptide', slots=['hand'])
SHARPNESS = CustomEnchantment(internal_name='sharpness', description='enchantment.minecraft.sharpness', slots=['mainhand'])
SILK_TOUCH = CustomEnchantment(internal_name='silk_touch', description='enchantment.minecraft.silk_touch', slots=['mainhand'])
SMITE = CustomEnchantment(internal_name='smite', description='enchantment.minecraft.smite', slots=['mainhand'])
SOUL_SPEED = CustomEnchantment(internal_name='soul_speed', description='enchantment.minecraft.soul_speed', slots=['feet'])
SWEEPING_EDGE = CustomEnchantment(internal_name='sweeping_edge', description='enchantment.minecraft.sweeping_edge', slots=['mainhand'])
SWIFT_SNEAK = CustomEnchantment(internal_name='swift_sneak', description='enchantment.minecraft.swift_sneak', slots=['legs'])
THORNS = CustomEnchantment(internal_name='thorns', description='enchantment.minecraft.thorns', slots=['any'])
UNBREAKING = CustomEnchantment(internal_name='unbreaking', description='enchantment.minecraft.unbreaking', slots=['any'])
VANISHING_CURSE = CustomEnchantment(internal_name='vanishing_curse', description='enchantment.minecraft.vanishing_curse', slots=['any'])
WIND_BURST = CustomEnchantment(internal_name='wind_burst', description='enchantment.minecraft.wind_burst', slots=['mainhand'])
