from pypacks.resources.custom_painting import CustomPainting


ALBAN = CustomPainting(internal_name='alban', image_path='alban', title='painting.minecraft.alban.title', author='painting.minecraft.alban.author')
AZTEC = CustomPainting(internal_name='aztec', image_path='aztec', title='painting.minecraft.aztec.title', author='painting.minecraft.aztec.author')
AZTEC2 = CustomPainting(internal_name='aztec2', image_path='aztec2', title='painting.minecraft.aztec2.title', author='painting.minecraft.aztec2.author')
BACKYARD = CustomPainting(internal_name='backyard', image_path='backyard', title='painting.minecraft.backyard.title', author='painting.minecraft.backyard.author', width_in_blocks=3, height_in_blocks=4)
BAROQUE = CustomPainting(internal_name='baroque', image_path='baroque', title='painting.minecraft.baroque.title', author='painting.minecraft.baroque.author', width_in_blocks=2, height_in_blocks=2)
BOMB = CustomPainting(internal_name='bomb', image_path='bomb', title='painting.minecraft.bomb.title', author='painting.minecraft.bomb.author')
BOUQUET = CustomPainting(internal_name='bouquet', image_path='bouquet', title='painting.minecraft.bouquet.title', author='painting.minecraft.bouquet.author', width_in_blocks=3, height_in_blocks=3)
BURNING_SKULL = CustomPainting(internal_name='burning_skull', image_path='burning_skull', title='painting.minecraft.burning_skull.title', author='painting.minecraft.burning_skull.author', width_in_blocks=4, height_in_blocks=4)
BUST = CustomPainting(internal_name='bust', image_path='bust', title='painting.minecraft.bust.title', author='painting.minecraft.bust.author', width_in_blocks=2, height_in_blocks=2)
CAVEBIRD = CustomPainting(internal_name='cavebird', image_path='cavebird', title='painting.minecraft.cavebird.title', author='painting.minecraft.cavebird.author', width_in_blocks=3, height_in_blocks=3)
CHANGING = CustomPainting(internal_name='changing', image_path='changing', title='painting.minecraft.changing.title', author='painting.minecraft.changing.author', width_in_blocks=4, height_in_blocks=2)
COTAN = CustomPainting(internal_name='cotan', image_path='cotan', title='painting.minecraft.cotan.title', author='painting.minecraft.cotan.author', width_in_blocks=3, height_in_blocks=3)
COURBET = CustomPainting(internal_name='courbet', image_path='courbet', title='painting.minecraft.courbet.title', author='painting.minecraft.courbet.author', width_in_blocks=2)
CREEBET = CustomPainting(internal_name='creebet', image_path='creebet', title='painting.minecraft.creebet.title', author='painting.minecraft.creebet.author', width_in_blocks=2)
DONKEY_KONG = CustomPainting(internal_name='donkey_kong', image_path='donkey_kong', title='painting.minecraft.donkey_kong.title', author='painting.minecraft.donkey_kong.author', width_in_blocks=4, height_in_blocks=3)
EARTH = CustomPainting(internal_name='earth', image_path='earth', title='painting.minecraft.earth.title', author='UNKNOWN', width_in_blocks=2, height_in_blocks=2)
ENDBOSS = CustomPainting(internal_name='endboss', image_path='endboss', title='painting.minecraft.endboss.title', author='painting.minecraft.endboss.author', width_in_blocks=3, height_in_blocks=3)
FERN = CustomPainting(internal_name='fern', image_path='fern', title='painting.minecraft.fern.title', author='painting.minecraft.fern.author', width_in_blocks=3, height_in_blocks=3)
FIGHTERS = CustomPainting(internal_name='fighters', image_path='fighters', title='painting.minecraft.fighters.title', author='painting.minecraft.fighters.author', width_in_blocks=4, height_in_blocks=2)
FINDING = CustomPainting(internal_name='finding', image_path='finding', title='painting.minecraft.finding.title', author='painting.minecraft.finding.author', width_in_blocks=4, height_in_blocks=2)
FIRE = CustomPainting(internal_name='fire', image_path='fire', title='painting.minecraft.fire.title', author='UNKNOWN', width_in_blocks=2, height_in_blocks=2)
GRAHAM = CustomPainting(internal_name='graham', image_path='graham', title='painting.minecraft.graham.title', author='painting.minecraft.graham.author', height_in_blocks=2)
HUMBLE = CustomPainting(internal_name='humble', image_path='humble', title='painting.minecraft.humble.title', author='painting.minecraft.humble.author', width_in_blocks=2, height_in_blocks=2)
KEBAB = CustomPainting(internal_name='kebab', image_path='kebab', title='painting.minecraft.kebab.title', author='painting.minecraft.kebab.author')
LOWMIST = CustomPainting(internal_name='lowmist', image_path='lowmist', title='painting.minecraft.lowmist.title', author='painting.minecraft.lowmist.author', width_in_blocks=4, height_in_blocks=2)
MATCH = CustomPainting(internal_name='match', image_path='match', title='painting.minecraft.match.title', author='painting.minecraft.match.author', width_in_blocks=2, height_in_blocks=2)
MEDITATIVE = CustomPainting(internal_name='meditative', image_path='meditative', title='painting.minecraft.meditative.title', author='painting.minecraft.meditative.author')
ORB = CustomPainting(internal_name='orb', image_path='orb', title='painting.minecraft.orb.title', author='painting.minecraft.orb.author', width_in_blocks=4, height_in_blocks=4)
OWLEMONS = CustomPainting(internal_name='owlemons', image_path='owlemons', title='painting.minecraft.owlemons.title', author='painting.minecraft.owlemons.author', width_in_blocks=3, height_in_blocks=3)
PASSAGE = CustomPainting(internal_name='passage', image_path='passage', title='painting.minecraft.passage.title', author='painting.minecraft.passage.author', width_in_blocks=4, height_in_blocks=2)
PIGSCENE = CustomPainting(internal_name='pigscene', image_path='pigscene', title='painting.minecraft.pigscene.title', author='painting.minecraft.pigscene.author', width_in_blocks=4, height_in_blocks=4)
PLANT = CustomPainting(internal_name='plant', image_path='plant', title='painting.minecraft.plant.title', author='painting.minecraft.plant.author')
POINTER = CustomPainting(internal_name='pointer', image_path='pointer', title='painting.minecraft.pointer.title', author='painting.minecraft.pointer.author', width_in_blocks=4, height_in_blocks=4)
POND = CustomPainting(internal_name='pond', image_path='pond', title='painting.minecraft.pond.title', author='painting.minecraft.pond.author', width_in_blocks=3, height_in_blocks=4)
POOL = CustomPainting(internal_name='pool', image_path='pool', title='painting.minecraft.pool.title', author='painting.minecraft.pool.author', width_in_blocks=2)
PRAIRIE_RIDE = CustomPainting(internal_name='prairie_ride', image_path='prairie_ride', title='painting.minecraft.prairie_ride.title', author='painting.minecraft.prairie_ride.author', height_in_blocks=2)
SEA = CustomPainting(internal_name='sea', image_path='sea', title='painting.minecraft.sea.title', author='painting.minecraft.sea.author', width_in_blocks=2)
SKELETON = CustomPainting(internal_name='skeleton', image_path='skeleton', title='painting.minecraft.skeleton.title', author='painting.minecraft.skeleton.author', width_in_blocks=4, height_in_blocks=3)
SKULL_AND_ROSES = CustomPainting(internal_name='skull_and_roses', image_path='skull_and_roses', title='painting.minecraft.skull_and_roses.title', author='painting.minecraft.skull_and_roses.author', width_in_blocks=2, height_in_blocks=2)
STAGE = CustomPainting(internal_name='stage', image_path='stage', title='painting.minecraft.stage.title', author='painting.minecraft.stage.author', width_in_blocks=2, height_in_blocks=2)
SUNFLOWERS = CustomPainting(internal_name='sunflowers', image_path='sunflowers', title='painting.minecraft.sunflowers.title', author='painting.minecraft.sunflowers.author', width_in_blocks=3, height_in_blocks=3)
SUNSET = CustomPainting(internal_name='sunset', image_path='sunset', title='painting.minecraft.sunset.title', author='painting.minecraft.sunset.author', width_in_blocks=2)
TIDES = CustomPainting(internal_name='tides', image_path='tides', title='painting.minecraft.tides.title', author='painting.minecraft.tides.author', width_in_blocks=3, height_in_blocks=3)
UNPACKED = CustomPainting(internal_name='unpacked', image_path='unpacked', title='painting.minecraft.unpacked.title', author='painting.minecraft.unpacked.author', width_in_blocks=4, height_in_blocks=4)
VOID = CustomPainting(internal_name='void', image_path='void', title='painting.minecraft.void.title', author='painting.minecraft.void.author', width_in_blocks=2, height_in_blocks=2)
WANDERER = CustomPainting(internal_name='wanderer', image_path='wanderer', title='painting.minecraft.wanderer.title', author='painting.minecraft.wanderer.author', height_in_blocks=2)
WASTELAND = CustomPainting(internal_name='wasteland', image_path='wasteland', title='painting.minecraft.wasteland.title', author='painting.minecraft.wasteland.author')
WATER = CustomPainting(internal_name='water', image_path='water', title='painting.minecraft.water.title', author='UNKNOWN', width_in_blocks=2, height_in_blocks=2)
WIND = CustomPainting(internal_name='wind', image_path='wind', title='painting.minecraft.wind.title', author='UNKNOWN', width_in_blocks=2, height_in_blocks=2)
WITHER = CustomPainting(internal_name='wither', image_path='wither', title='painting.minecraft.wither.title', author='UNKNOWN', width_in_blocks=2, height_in_blocks=2)

ALL_PAINTINGS = [
    ALBAN, AZTEC, AZTEC2, BACKYARD, BAROQUE, BOMB, BOUQUET, BURNING_SKULL, BUST, CAVEBIRD, CHANGING, COTAN, COURBET, CREEBET, DONKEY_KONG, EARTH, ENDBOSS, FERN, FIGHTERS, FINDING, FIRE, GRAHAM, HUMBLE, KEBAB, LOWMIST, MATCH, MEDITATIVE, ORB, OWLEMONS, PASSAGE, PIGSCENE, PLANT, POINTER, POND, POOL, PRAIRIE_RIDE, SEA, SKELETON, SKULL_AND_ROSES, STAGE, SUNFLOWERS, SUNSET, TIDES, UNPACKED, VOID, WANDERER, WASTELAND, WATER, WIND, WITHER
]
